services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env.docker
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - backend

  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5001:5001
    env_file:
      - .env.docker
    volumes:
      - ./:/app
      - /app/app/node_modules
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
